server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

flyway:
  enabled: true
  locations: classpath:db/migration

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true