server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

flyway:
  enabled: true
  locations: classpath:db/migration

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true